# Each service uses images we've built and pushed to our repo's GHCR
# The script that controls those images is found here - .gitub/workflows/DeployToGHCR.yml

services:
  bucstop:
    image: ghcr.io/andersonjb1/bucstop-qwerty/webapp:latest
    container_name: bucstop
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - bucstop-network
    environment:
      - DOTNET_ENVIRONMENT=${env:-containers}
      - GIT_COMMIT_HASH=${GIT_COMMIT:-unknown}
    #depends_on:
    #  - api-gateway
    volumes:
      - snapshots-data:/app/Snapshots
      - logs-data:/app/Logs
      - submission-data:/app/Submissions

  api-gateway:
    image: ghcr.io/andersonjb1/bucstop-qwerty/gateway:latest
    container_name: api-gateway
    restart: unless-stopped
    ports:
      - "8081:80" # Expose API Gateway on localhost:8081
    networks:
      - bucstop-network
    environment:
      - DOTNET_ENVIRONMENT=${env:-containers}
    #depends_on:
    #  - snake
    #  - pong
    #  - tetris

  snake:
    image: ghcr.io/andersonjb1/bucstop-qwerty/snake:latest
    container_name: game-snake
    restart: unless-stopped
    environment:
      - DOTNET_ENVIRONMENT=${env:-containers}
    ports:
      - "8082:80" # Expose Snake microservice on localhost:8082
    networks:
      - bucstop-network

  pong:
    image: ghcr.io/andersonjb1/bucstop-qwerty/pong:latest
    container_name: game-pong
    restart: unless-stopped
    environment:
      - DOTNET_ENVIRONMENT=${env:-containers}
    ports:
      - "8083:80" # Expose Pong microservice on localhost:8083
    networks:
      - bucstop-network

  tetris:
    image: ghcr.io/andersonjb1/bucstop-qwerty/tetris:latest
    container_name: game-tetris
    restart: unless-stopped
    environment:
      - DOTNET_ENVIRONMENT=${env:-containers}
    ports:
      - "8084:80" # Expose Tetris microservice on localhost:8084
    networks:
      - bucstop-network

  submission-gateway:
    image: "ghcr.io/andersonjb1/bucstop-qwerty/submission-gateway:latest"
    container_name: submission-gateway
    restart: unless-stopped
    ports:
      - "8085:80"
    networks:
      - bucstop-network
    environment:
      - DOTNET_ENVIRONMENT=${env:-containers}
    volumes:
      - submission-data:/app/Submissions

  # Watchtower is an all in one CI/CD tool that allows us to periodically
  # check and see if our containers can be updated. If they can, it performs a
  # rolling update to the ones who need it.
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    ports:
      - "9000:80"
    networks:
      - bucstop-network
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # The following commands:
    # interval - the interval watchtower will check our container images
    # cleanup - removes the older images after the update
    # rolling-restart - updates one container at a time
    command: >
      --interval 30
      --cleanup
      --rolling-restart
    environment:
      - TZ=America/New_York # set your timezone (e.g. America/New_York)

networks:
  bucstop-network:
    driver: bridge

volumes:
  snapshots-data:
    driver: local
  logs-data:
    driver: local
  submission-data:
    driver: local
